meta_product_name: "Zenkey"
meta_title: "Zenkey"
meta_description: "La première agence immobilière gratuite"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@homepay_social"
